/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TabletRouteImport } from './routes/tablet'
import { Route as OrderTypeRouteImport } from './routes/order-type'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemItemIdRouteImport } from './routes/item.$itemId'
import { Route as ConfirmationOrderIdRouteImport } from './routes/confirmation.$orderId'

const TabletRoute = TabletRouteImport.update({
  id: '/tablet',
  path: '/tablet',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderTypeRoute = OrderTypeRouteImport.update({
  id: '/order-type',
  path: '/order-type',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemItemIdRoute = ItemItemIdRouteImport.update({
  id: '/item/$itemId',
  path: '/item/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationOrderIdRoute = ConfirmationOrderIdRouteImport.update({
  id: '/confirmation/$orderId',
  path: '/confirmation/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/menu': typeof MenuRoute
  '/order-type': typeof OrderTypeRoute
  '/tablet': typeof TabletRoute
  '/confirmation/$orderId': typeof ConfirmationOrderIdRoute
  '/item/$itemId': typeof ItemItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/menu': typeof MenuRoute
  '/order-type': typeof OrderTypeRoute
  '/tablet': typeof TabletRoute
  '/confirmation/$orderId': typeof ConfirmationOrderIdRoute
  '/item/$itemId': typeof ItemItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/menu': typeof MenuRoute
  '/order-type': typeof OrderTypeRoute
  '/tablet': typeof TabletRoute
  '/confirmation/$orderId': typeof ConfirmationOrderIdRoute
  '/item/$itemId': typeof ItemItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/menu'
    | '/order-type'
    | '/tablet'
    | '/confirmation/$orderId'
    | '/item/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/menu'
    | '/order-type'
    | '/tablet'
    | '/confirmation/$orderId'
    | '/item/$itemId'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/menu'
    | '/order-type'
    | '/tablet'
    | '/confirmation/$orderId'
    | '/item/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  MenuRoute: typeof MenuRoute
  OrderTypeRoute: typeof OrderTypeRoute
  TabletRoute: typeof TabletRoute
  ConfirmationOrderIdRoute: typeof ConfirmationOrderIdRoute
  ItemItemIdRoute: typeof ItemItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tablet': {
      id: '/tablet'
      path: '/tablet'
      fullPath: '/tablet'
      preLoaderRoute: typeof TabletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-type': {
      id: '/order-type'
      path: '/order-type'
      fullPath: '/order-type'
      preLoaderRoute: typeof OrderTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$itemId': {
      id: '/item/$itemId'
      path: '/item/$itemId'
      fullPath: '/item/$itemId'
      preLoaderRoute: typeof ItemItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation/$orderId': {
      id: '/confirmation/$orderId'
      path: '/confirmation/$orderId'
      fullPath: '/confirmation/$orderId'
      preLoaderRoute: typeof ConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  MenuRoute: MenuRoute,
  OrderTypeRoute: OrderTypeRoute,
  TabletRoute: TabletRoute,
  ConfirmationOrderIdRoute: ConfirmationOrderIdRoute,
  ItemItemIdRoute: ItemItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
