/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TabletRouteImport } from './routes/tablet'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OrderTypeRouteImport } from './routes/order-type'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StaffLoginRouteImport } from './routes/staff.login'
import { Route as ItemSlugRouteImport } from './routes/item.$slug'
import { Route as ConfirmationOrderIdRouteImport } from './routes/confirmation.$orderId'
import { Route as AdminZonesRouteImport } from './routes/admin.zones'
import { Route as AdminThrottleRouteImport } from './routes/admin.throttle'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPromosRouteImport } from './routes/admin.promos'
import { Route as AdminModifiersRouteImport } from './routes/admin.modifiers'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminHoursRouteImport } from './routes/admin.hours'
import { Route as AdminDriversRouteImport } from './routes/admin.drivers'
import { Route as AdminClosuresRouteImport } from './routes/admin.closures'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBiyoRouteImport } from './routes/admin.biyo'
import { Route as ApiPublicHooksSyncBiyoRouteImport } from './routes/api/public/hooks/sync-biyo'
import { Route as ApiPublicHooksShipdayRouteImport } from './routes/api/public/hooks/shipday'
import { Route as ApiPublicHooksCartAbandonmentRouteImport } from './routes/api/public/hooks/cart-abandonment'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TabletRoute = TabletRouteImport.update({
  id: '/tablet',
  path: '/tablet',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderTypeRoute = OrderTypeRouteImport.update({
  id: '/order-type',
  path: '/order-type',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemSlugRoute = ItemSlugRouteImport.update({
  id: '/item/$slug',
  path: '/item/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationOrderIdRoute = ConfirmationOrderIdRouteImport.update({
  id: '/confirmation/$orderId',
  path: '/confirmation/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminZonesRoute = AdminZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminThrottleRoute = AdminThrottleRouteImport.update({
  id: '/throttle',
  path: '/throttle',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromosRoute = AdminPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModifiersRoute = AdminModifiersRouteImport.update({
  id: '/modifiers',
  path: '/modifiers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHoursRoute = AdminHoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClosuresRoute = AdminClosuresRouteImport.update({
  id: '/closures',
  path: '/closures',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBiyoRoute = AdminBiyoRouteImport.update({
  id: '/biyo',
  path: '/biyo',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksSyncBiyoRoute = ApiPublicHooksSyncBiyoRouteImport.update({
  id: '/api/public/hooks/sync-biyo',
  path: '/api/public/hooks/sync-biyo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksShipdayRoute = ApiPublicHooksShipdayRouteImport.update({
  id: '/api/public/hooks/shipday',
  path: '/api/public/hooks/shipday',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCartAbandonmentRoute =
  ApiPublicHooksCartAbandonmentRouteImport.update({
    id: '/api/public/hooks/cart-abandonment',
    path: '/api/public/hooks/cart-abandonment',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dispatch': typeof DispatchRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/order-type': typeof OrderTypeRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tablet': typeof TabletRoute
  '/terms': typeof TermsRoute
  '/admin/biyo': typeof AdminBiyoRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/closures': typeof AdminClosuresRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/hours': typeof AdminHoursRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/modifiers': typeof AdminModifiersRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/throttle': typeof AdminThrottleRoute
  '/admin/zones': typeof AdminZonesRoute
  '/confirmation/$orderId': typeof ConfirmationOrderIdRoute
  '/item/$slug': typeof ItemSlugRoute
  '/staff/login': typeof StaffLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/hooks/cart-abandonment': typeof ApiPublicHooksCartAbandonmentRoute
  '/api/public/hooks/shipday': typeof ApiPublicHooksShipdayRoute
  '/api/public/hooks/sync-biyo': typeof ApiPublicHooksSyncBiyoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dispatch': typeof DispatchRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/order-type': typeof OrderTypeRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tablet': typeof TabletRoute
  '/terms': typeof TermsRoute
  '/admin/biyo': typeof AdminBiyoRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/closures': typeof AdminClosuresRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/hours': typeof AdminHoursRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/modifiers': typeof AdminModifiersRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/throttle': typeof AdminThrottleRoute
  '/admin/zones': typeof AdminZonesRoute
  '/confirmation/$orderId': typeof ConfirmationOrderIdRoute
  '/item/$slug': typeof ItemSlugRoute
  '/staff/login': typeof StaffLoginRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/hooks/cart-abandonment': typeof ApiPublicHooksCartAbandonmentRoute
  '/api/public/hooks/shipday': typeof ApiPublicHooksShipdayRoute
  '/api/public/hooks/sync-biyo': typeof ApiPublicHooksSyncBiyoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/dispatch': typeof DispatchRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/order-type': typeof OrderTypeRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tablet': typeof TabletRoute
  '/terms': typeof TermsRoute
  '/admin/biyo': typeof AdminBiyoRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/closures': typeof AdminClosuresRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/hours': typeof AdminHoursRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/modifiers': typeof AdminModifiersRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/throttle': typeof AdminThrottleRoute
  '/admin/zones': typeof AdminZonesRoute
  '/confirmation/$orderId': typeof ConfirmationOrderIdRoute
  '/item/$slug': typeof ItemSlugRoute
  '/staff/login': typeof StaffLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/hooks/cart-abandonment': typeof ApiPublicHooksCartAbandonmentRoute
  '/api/public/hooks/shipday': typeof ApiPublicHooksShipdayRoute
  '/api/public/hooks/sync-biyo': typeof ApiPublicHooksSyncBiyoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/dispatch'
    | '/forgot-password'
    | '/login'
    | '/menu'
    | '/order-type'
    | '/privacy'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/tablet'
    | '/terms'
    | '/admin/biyo'
    | '/admin/categories'
    | '/admin/closures'
    | '/admin/drivers'
    | '/admin/hours'
    | '/admin/menu'
    | '/admin/modifiers'
    | '/admin/promos'
    | '/admin/reports'
    | '/admin/staff'
    | '/admin/throttle'
    | '/admin/zones'
    | '/confirmation/$orderId'
    | '/item/$slug'
    | '/staff/login'
    | '/admin/'
    | '/api/public/hooks/cart-abandonment'
    | '/api/public/hooks/shipday'
    | '/api/public/hooks/sync-biyo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/dispatch'
    | '/forgot-password'
    | '/login'
    | '/menu'
    | '/order-type'
    | '/privacy'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/tablet'
    | '/terms'
    | '/admin/biyo'
    | '/admin/categories'
    | '/admin/closures'
    | '/admin/drivers'
    | '/admin/hours'
    | '/admin/menu'
    | '/admin/modifiers'
    | '/admin/promos'
    | '/admin/reports'
    | '/admin/staff'
    | '/admin/throttle'
    | '/admin/zones'
    | '/confirmation/$orderId'
    | '/item/$slug'
    | '/staff/login'
    | '/admin'
    | '/api/public/hooks/cart-abandonment'
    | '/api/public/hooks/shipday'
    | '/api/public/hooks/sync-biyo'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/dispatch'
    | '/forgot-password'
    | '/login'
    | '/menu'
    | '/order-type'
    | '/privacy'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/tablet'
    | '/terms'
    | '/admin/biyo'
    | '/admin/categories'
    | '/admin/closures'
    | '/admin/drivers'
    | '/admin/hours'
    | '/admin/menu'
    | '/admin/modifiers'
    | '/admin/promos'
    | '/admin/reports'
    | '/admin/staff'
    | '/admin/throttle'
    | '/admin/zones'
    | '/confirmation/$orderId'
    | '/item/$slug'
    | '/staff/login'
    | '/admin/'
    | '/api/public/hooks/cart-abandonment'
    | '/api/public/hooks/shipday'
    | '/api/public/hooks/sync-biyo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  DispatchRoute: typeof DispatchRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  OrderTypeRoute: typeof OrderTypeRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TabletRoute: typeof TabletRoute
  TermsRoute: typeof TermsRoute
  ConfirmationOrderIdRoute: typeof ConfirmationOrderIdRoute
  ItemSlugRoute: typeof ItemSlugRoute
  StaffLoginRoute: typeof StaffLoginRoute
  ApiPublicHooksCartAbandonmentRoute: typeof ApiPublicHooksCartAbandonmentRoute
  ApiPublicHooksShipdayRoute: typeof ApiPublicHooksShipdayRoute
  ApiPublicHooksSyncBiyoRoute: typeof ApiPublicHooksSyncBiyoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tablet': {
      id: '/tablet'
      path: '/tablet'
      fullPath: '/tablet'
      preLoaderRoute: typeof TabletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-type': {
      id: '/order-type'
      path: '/order-type'
      fullPath: '/order-type'
      preLoaderRoute: typeof OrderTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$slug': {
      id: '/item/$slug'
      path: '/item/$slug'
      fullPath: '/item/$slug'
      preLoaderRoute: typeof ItemSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation/$orderId': {
      id: '/confirmation/$orderId'
      path: '/confirmation/$orderId'
      fullPath: '/confirmation/$orderId'
      preLoaderRoute: typeof ConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/zones': {
      id: '/admin/zones'
      path: '/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AdminZonesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/throttle': {
      id: '/admin/throttle'
      path: '/throttle'
      fullPath: '/admin/throttle'
      preLoaderRoute: typeof AdminThrottleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promos': {
      id: '/admin/promos'
      path: '/promos'
      fullPath: '/admin/promos'
      preLoaderRoute: typeof AdminPromosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modifiers': {
      id: '/admin/modifiers'
      path: '/modifiers'
      fullPath: '/admin/modifiers'
      preLoaderRoute: typeof AdminModifiersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hours': {
      id: '/admin/hours'
      path: '/hours'
      fullPath: '/admin/hours'
      preLoaderRoute: typeof AdminHoursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/closures': {
      id: '/admin/closures'
      path: '/closures'
      fullPath: '/admin/closures'
      preLoaderRoute: typeof AdminClosuresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/biyo': {
      id: '/admin/biyo'
      path: '/biyo'
      fullPath: '/admin/biyo'
      preLoaderRoute: typeof AdminBiyoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/sync-biyo': {
      id: '/api/public/hooks/sync-biyo'
      path: '/api/public/hooks/sync-biyo'
      fullPath: '/api/public/hooks/sync-biyo'
      preLoaderRoute: typeof ApiPublicHooksSyncBiyoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/shipday': {
      id: '/api/public/hooks/shipday'
      path: '/api/public/hooks/shipday'
      fullPath: '/api/public/hooks/shipday'
      preLoaderRoute: typeof ApiPublicHooksShipdayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cart-abandonment': {
      id: '/api/public/hooks/cart-abandonment'
      path: '/api/public/hooks/cart-abandonment'
      fullPath: '/api/public/hooks/cart-abandonment'
      preLoaderRoute: typeof ApiPublicHooksCartAbandonmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBiyoRoute: typeof AdminBiyoRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminClosuresRoute: typeof AdminClosuresRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminHoursRoute: typeof AdminHoursRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminModifiersRoute: typeof AdminModifiersRoute
  AdminPromosRoute: typeof AdminPromosRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminThrottleRoute: typeof AdminThrottleRoute
  AdminZonesRoute: typeof AdminZonesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBiyoRoute: AdminBiyoRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminClosuresRoute: AdminClosuresRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminHoursRoute: AdminHoursRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminModifiersRoute: AdminModifiersRoute,
  AdminPromosRoute: AdminPromosRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminThrottleRoute: AdminThrottleRoute,
  AdminZonesRoute: AdminZonesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  DispatchRoute: DispatchRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  OrderTypeRoute: OrderTypeRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TabletRoute: TabletRoute,
  TermsRoute: TermsRoute,
  ConfirmationOrderIdRoute: ConfirmationOrderIdRoute,
  ItemSlugRoute: ItemSlugRoute,
  StaffLoginRoute: StaffLoginRoute,
  ApiPublicHooksCartAbandonmentRoute: ApiPublicHooksCartAbandonmentRoute,
  ApiPublicHooksShipdayRoute: ApiPublicHooksShipdayRoute,
  ApiPublicHooksSyncBiyoRoute: ApiPublicHooksSyncBiyoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
